name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  typecheck-lint-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run typecheck --if-present
      - run: npm run lint --if-present

  build:
    runs-on: ubuntu-latest
    needs: typecheck-lint-unit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build
        env:
          TMDB_READ_TOKEN: ${{ secrets.TMDB_READ_TOKEN }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          GITHUB_ID: ${{ secrets.OAUTH_GITHUB_ID }}
          GITHUB_SECRET: ${{ secrets.OAUTH_GITHUB_SECRET }}
          NEXTAUTH_URL: http://localhost:3000

  # e2e:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #         cache: 'npm'
  #     - run: npm ci
  #     - run: npm run build
  #       env:
  #         TMDB_READ_TOKEN: ${{ secrets.TMDB_READ_TOKEN }}
  #         NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  #         GITHUB_ID: ${{ secrets.OAUTH_GITHUB_ID }}
  #         GITHUB_SECRET: ${{ secrets.OAUTH_GITHUB_SECRET }}
  #         NEXTAUTH_URL: http://localhost:3000
  #     - name: Cypress run (E2E)
  #       uses: cypress-io/github-action@v6
  #       with:
  #         start: npm start
  #         wait-on: 'http://localhost:3000'
  #       env:
  #         TMDB_READ_TOKEN: ${{ secrets.TMDB_READ_TOKEN }}
  #         NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  #         GITHUB_ID: ${{ secrets.OAUTH_GITHUB_ID }}
  #         GITHUB_SECRET: ${{ secrets.OAUTH_GITHUB_SECRET }}
  #         NEXTAUTH_URL: http://localhost:3000
